export enum BlueFarmActionType {
  LOAD_USER = "LOAD_USER",
  LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS",
  LOAD_USER_FAIL = "LOAD_USER_FAIL",

  AUTHENTICATE_LOADING = "AUTHENTICATE_LOADING",
  AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS",
  AUTHENTICATE_FAIL = "AUTHENTICATE_FAIL",
  LOGOUT_LOADING = "LOGOUT_LOADING",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
  LOGOUT_FAIL = "LOGOUT_FAIL",

  APP_STATE_LOADING = "APP_STATE_LOADING",
}

export interface Action<T> {
  type: BlueFarmActionType;
  payload?: T;
}
